# Generated by Django 3.0.3 on 2020-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
